apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kopf-operator-metrics
  namespace: hse-llm-project
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - hse-llm-project
  selector:
    matchLabels:
      app.kubernetes.io/name: llmdeployment-vllm-controller
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
