apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tuya-smart-plug-exporter-metrics
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/name: tuya-smart-plug-exporter
      app.kubernetes.io/instance: tuya-smart-plug-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
