apiVersion: v1
kind: Service
metadata:
  name: tuya-smart-plug-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: tuya-smart-plug-exporter
    app.kubernetes.io/instance: tuya-smart-plug-exporter
spec:
  selector:
    app.kubernetes.io/name: tuya-smart-plug-exporter
    app.kubernetes.io/instance: tuya-smart-plug-exporter
  ports:
    - name: http
      port: 9122
      targetPort: http
      protocol: TCP
