apiVersion: gateway.networking.k8s.io/v1
kind: ReferenceGrant
metadata:
  name: allow-hse-route-to-grafana
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: monitoring
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: hse-llm-project
  to:
    - group: ""
      kind: Service
      name: kube-prometheus-stack-grafana
