apiVersion: v1
kind: Service
metadata:
  name: nut-ups-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: nut-ups-exporter
    app.kubernetes.io/instance: nut-ups-exporter
spec:
  selector:
    app.kubernetes.io/name: nut-ups-exporter
    app.kubernetes.io/instance: nut-ups-exporter
  ports:
    - name: http
      port: 9199
      targetPort: http
      protocol: TCP
